package com.imrul.replog.core

object Constants {
    const val WORKOUT_DATABASE_NAME = "workout_db"
    const val MEASUREMENT_DATABASE_NAME = "measurement_db"
    const val TEST_DATABASE_NAME = "test_workout_db"
    const val WORKOUT_NOTIFICATION_CHANNEL_ID = "workout_channel"
    const val EMAIL_PLACEHOLDER = "Email"
    const val MESSAGES_PLACEHOLDER = "Messages"
    const val MESSAGE_PLACEHOLDER = "Message"
    const val COURSES_PLACEHOLDER = "Courses"
    const val USERNAME_PLACEHOLDER = "Username"
    const val PASSWORD_PLACEHOLDER = "Password"
    const val CONFIRM_PASSWORD_PLACEHOLDER = "Confirm Password"
    const val ALREADY_HAVE_AN_ACCOUNT = "Already have an account? "
    const val DO_NOT_HAVE_AN_ACCOUNT = "Don't have an account? "
    const val SIGN_IN = "Sign In"
    const val SIGN_OUT = "Sign Out"
    const val SIGN_UP = "Sign Up"
    const val LINK_ACCOUNT = "Link Account"
    const val SIGN_UP_WITH = "Sign Up with"
    const val SIGN_IN_WITH = "Sign In with"
    const val CONTINUE_AS_GUEST = "Continue as a guest"
    const val USERNAME_REGEX = "^[A-Za-z][A-Za-z0-9_]{5,12}$"
    const val USERS_COLLECTION = "users"
    const val EXERCISES_COLLECTION = "exercises"
    const val MEASUREMENTS_COLLECTION = "measurements"
    const val NOTES_COLLECTION = "notes"
    const val SESSIONS_COLLECTION = "sessions"
    const val SETS_COLLECTION = "sets"
    const val WORKOUTS_COLLECTION = "workouts"

}
